import { existsSync, readFileSync, writeFileSync } from "node:fs";
import Ajv from "ajv";
import standalone from "ajv/dist/standalone";
import { schemas } from "../src/schemas/definitions";

const ajv = new Ajv({
  allErrors: true,
  allowUnionTypes: true,
  code: { source: true, esm: true },
});
for (const [name, schema] of Object.entries(schemas))
  ajv.addSchema(schema, name);
let code = standalone(ajv, {
  map: "map",
  character: "character",
  sound: "sound",
});
code = code.replace(
  /require\("ajv\/dist\/runtime\/ucs2length"\)\.default/g,
  "ucs2length",
);
const destination = new URL("../src/schemas/generated.js", import.meta.url);
const source =
  "// Generated by bun run schemas. Do not edit.\nfunction ucs2length(value) { return Array.from(value).length; }\n" +
  code;
// Avoid triggering the user's live dev server when another test/build runs.
if (!existsSync(destination) || readFileSync(destination, "utf8") !== source)
  writeFileSync(destination, source);
